### ISSUE TITLE
Video dillemma

### ISSUE THREAD

**Issue by onweru** [ericwjr/notice#1]
I did not include the videos as specified. If I were to include the videos, the question would be if you guys have videos for the app.
If yes, I will go ahead an put the video backgrounds.
If no, then I would recommend the *svgs* on the app itself. 
Let me know what  you think.

**Comment by ericwjr** [comment]
Just need placeholders for now.  I want to just see if we can duplicate that effect.  I'm working on the video content.

**Comment by onweru** [comment]
Perfecto
