### ISSUE TITLE
Slider timed transitions

### ISSUE THREAD

**Issue by blakeblake** [ericwjr/notice#10]
Is it a possibility to not have the slider time based and gesture or interaction based off of a user's mouse onclick or something controlled by the user and not timed. @ericwjr

**Comment by ericwjr** [comment]
Right now it responds on swipe but not on click.  @onweru can you add on-click

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blakeblake** [comment]
@ericwjr @onweru Actually, after giving this further thought this should be a initial dom load thing only. I think that may be best for the landing

**Comment by ericwjr** [comment]
Yep, it should be all three...on-swipe, on-click, and on-timer.  That's typically how sliders are implemented.

**Comment by ericwjr** [comment]
on-click is not mouse click by the way...more like keyboard direction pad click...(left, right)

**Comment by ericwjr** [comment]
Still need keyboard left/right

**Comment by ericwjr** [comment]
Slider timing is there

**Comment by ericwjr** [comment]
https://lh3.googleusercontent.com/-WJCE4GNGvTo/WUdE72p11DI/AAAAAAABM3U/RkciVYcE6qAjwQm1ljA2KlR2XKiWe7gfACL0BGAYYCw/h1920/1688056703322489986%253Faccount_id%253D1

Responsiveness not quite right...text getting cut off.  Compared to:

https://lh3.googleusercontent.com/-ArcW8uu5P-U/WUdFSfpmk9I/AAAAAAABM3U/H-SosDJcEPANaPfRu6n70mLGkgi2yaTVACL0BGAYYCw/h1920/2300390375452432344%253Faccount_id%253D1

**Comment by onweru** [comment]
Fixed

**Comment by ericwjr** [comment]
Yep...timer a little too fast now though

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ericwjr** [comment]
Should respond to keyboard left/right keypress as well.

**Comment by ericwjr** [comment]
This is still open

**Comment by onweru** [comment]
Yep

**Comment by ericwjr** [comment]
Let me know when this is closed...

**Comment by onweru** [comment]
Sure

**Comment by onweru** [comment]
Next in line

**Comment by blakeblake** [comment]
this still needs some more attention. Does not feel smooth.

**Comment by ericwjr** [comment]
Download app image link should not animate out

All the text below it should animate in together
