### ISSUE TITLE
Chat icon placement

### ISSUE THREAD

**Issue by blakeblake** [ericwjr/notice#11]
if chat logo is essential to desired UI, bottom right as opposed to top right placement. Would recommend doing away with icon all together

**Comment by ericwjr** [comment]
Not essential, will remove icon... Will just be included statically on home page after UI wireframe section

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blakeblake** [comment]
cool, closing this
