### ISSUE TITLE
Edit assets/look.png 

### ISSUE THREAD

**Issue by onweru** [ericwjr/notice#12]
@blakeblake 
Kindly help me chop off the parts I have highlighted in red. The original image is in the assets folder. Preserve the transparent background. Thanks.
![img_0009](https://user-images.githubusercontent.com/16350351/26953808-49c7315a-4cb5-11e7-8f8f-a36555704b59.JPG)

**Comment by blakeblake** [comment]
@onweru , so you are looking to specifically have only the phone ? let me know and i can get that done for you.

**Comment by ericwjr** [comment]
@blakeblake no he's saying he only wants the partial hand with the wrist and phone removed

**Comment by blakeblake** [comment]
@ericwjr @onweru Hey there man, 

so i'm going to have to honestly recreate that hand which i am currently doing. As mentioned I am doing and it is possible but not really the best corse. Will def take a little time and will look pretty similar to the original artist work. we can do this but really recommending a stock hand or something along those lines from shutterstock etc.

**Comment by blakeblake** [comment]
Ok so we are going to go ahead and proceed with a stockholder hand. Will give us the same desired effect and a lot faster. 
@onweru  @ericwjr

**Comment by onweru** [comment]
Alright
