### ISSUE TITLE
UI Showcase View

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#14]
Phone with UI with features around it.

Features: (Layout:  Heading then text)

You are in Control
You control what apps can notify you and how you want to be notified...speakers, lights, etc

In-home PA System
Save your voice and send your messages through your home's speakers

Smart
Notice automatically enables when on your home wifi and disables when you leave

Quick Access
Quickly pause or broadcast from the app's notification actions

Room by Room Control
Only broadcast notifications to the rooms you choose

Personalize
Customize notification with custom tones

**Comment by ericwjr** [comment]
Not responsive

https://lh3.googleusercontent.com/-oBHbdaeQz2A/WUL06ZuCAmI/AAAAAAABMxU/Qq0-Sbr1-q0QvUmzz6GNC3zTj6PSw3uEACL0BGAYYCw/h614/2017-06-15.png

**Comment by ericwjr** [comment]
the text should be symmetric on left and right

**Comment by ericwjr** [comment]
2 Nav bars...no bueno

**Comment by ericwjr** [comment]
The incoming hand is not working out...let's drop it.

**Comment by onweru** [comment]
Navbar issue fixed

**Comment by ericwjr** [comment]
Looks good... Only thing: transition timer slightly too fast.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ericwjr** [comment]
Nav bar should not transition out between screens... It should be static

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by onweru** [comment]
solved

**Comment by ericwjr** [comment]
Solved but nav bar is slightly off.  Swap the app-picker icon with the back icon as seen below

![image](https://user-images.githubusercontent.com/5182394/27514383-0f0792cc-5957-11e7-96a2-6015c3998411.png)

**Comment by ericwjr** [comment]
Also text is so far from phone...bring it in a little closer.
