### ISSUE TITLE
Need 4th section after UI showcase for video

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#15]

**Comment by onweru** [comment]
More video or?

**Comment by ericwjr** [comment]
Yeah they'll be another video, more like commercial... Use a placeholder video for now.  No auto play, just big play button in the middle of video that will start it when pressed

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by onweru** [comment]
Perfect. I will have in place

**Comment by ericwjr** [comment]
Play/pause button is weird...no pause...only play button shown when paused....remove circle from around play button

**Comment by ericwjr** [comment]
Perfect
