### ISSUE TITLE
Icon pack

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#17]
See if you can find better iconography for the UI showcase view

**Comment by blakeblake** [comment]
https://www.sketchappsources.com/free-source/2703-line-icons-sketch-freebie-resource.html

**Comment by blakeblake** [comment]
https://www.sketchappsources.com/free-source/8-icons-set-kit.html

**Comment by blakeblake** [comment]
https://www.sketchappsources.com/free-source/1887-pausrr-icon-set-sketch-freebie-resource.html

**Comment by ericwjr** [comment]
Yep...I like Pausrr

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
