### ISSUE TITLE
Top right should be nav widget

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#21]
Similar to https://www.looklisten.com/

Navigates to sections in single page site

- Home
- UI
- Video
- Contact Us

**Comment by onweru** [comment]
Fixed

**Comment by ericwjr** [comment]
Looks good, background should be more opaque tho

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ericwjr** [comment]
something similar to this
http://www.hugeinc.com/

**Comment by ericwjr** [comment]
This still isn't right.  The animation shows menu twice.

**Comment by ericwjr** [comment]
Text should be same font as the rest as site...and a little larger.

**Comment by ericwjr** [comment]
Also use a different color as background...like a dark gold
