### ISSUE TITLE
Better text symmetry formatting 

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#22]
Text should have a max and min distance away from phone...

When you go full screen...text seems too far away, bring it in 
![image](https://user-images.githubusercontent.com/5182394/27710379-824cb5ac-5ced-11e7-87ba-278d461844de.png)

**Comment by onweru** [comment]
Fixed

**Comment by blakeblake** [comment]
still "very wide". Icons with informational excerpt should be closer to the phone

**Comment by blakeblake** [comment]
actually, this is better, marking this closed.
