### ISSUE TITLE
Refactor download icon

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#24]

**Comment by blakeblake** [comment]
![dl-png](https://user-images.githubusercontent.com/4462085/27917897-59516c4e-623b-11e7-9e01-8a024a55c4d3.png)
![revised-andriod](https://user-images.githubusercontent.com/4462085/27917896-59503f18-623b-11e7-92a2-18b21a822499.png)

**Comment by blakeblake** [comment]
we def need something like these but i'm trying to find a high res android guy in white

**Comment by ericwjr** [comment]
Your image doesn't show

**Comment by blakeblake** [comment]
still need to figure out proper rendering size but can be closed @ericwjr

**Comment by blakeblake** [comment]
new asset has been uploaded
