### ISSUE TITLE
Have to click before pressing directional arrow (SLIDER)

### ISSUE THREAD

**Issue by blakeblake** [ericwjr/notice#27]
@onweru you should not have to click then press directional key to progress to next slide on homepage/landig

**Comment by onweru** [comment]
I tried to solve this issue by replacing bootstrap with slick js. The result was aweful. We agreed with @ericwjr to rollback until such a time I can figure to manipulate bootstrap's keyboard navigation.

**Comment by onweru** [comment]
same as issue #10
