### ISSUE TITLE
Icon reset 

### ISSUE THREAD

**Issue by blakeblake** [ericwjr/notice#28]
After new icon placement.. refreshing page "resets" or takes away new logos that are desired. not sure about this. please meesage as soon as possible 

@onweru

**Comment by onweru** [comment]
Hey Blake, how do you mean? I don't follow.

**Comment by blakeblake** [comment]
Was able to dynamically upload "icons" in the "data" folder/yml file format however after rendering after saving.. they will.. not render and previous set will appear.

**Comment by blakeblake** [comment]
*Dynamically reference
